/**
 * 术语库 · 国内机关名称（**自动生成，不要手改**）
 *
 * 来源：仓库根目录的 `国内机构.docx`。
 * 生成命令：node scripts/build-terms.mjs --write
 *
 * 每条：`zh` 中文名、`en` 官方英文（照文档原样，括号统一成半角）、
 * `enAlt` 一并算对的其它英文写法（官方缩写与英美拼写变体）、
 * `zhAlt` 英译中方向下同样算对的其它中文名（一英多中，如「直辖市人民政府」与「设区的市人民政府」）。
 */

import type { Term } from '../terms'

export const CN_ORG_TERMS: readonly Term[] = [
  {
    zh: "中国共产党中央委员会",
    en: "Central Committee of the Communist Party of China(CPC Central Committee)",
    enAlt: ["CPC Central Committee"],
    zhAlt: [],
  },
  {
    zh: "中央政治局",
    en: "Political Bureau of the CPC Central Committee",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中央政治局常务委员会",
    en: "Standing Committee of the Political Bureau of the CPC",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中央书记处",
    en: "Secretariat of the CPC Central Committee",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中共中央办公厅",
    en: "General Office of the CPC Central Committee",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中共中央组织部",
    en: "Organization Department of the CPC Central Committee",
    enAlt: ["Organisation Department of the CPC Central Committee"],
    zhAlt: [],
  },
  {
    zh: "中共中央宣传部",
    en: "Publicity Department of the CPC Central Committee",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中共中央统一战线工作部",
    en: "United Front Work Department of the CPC Central Committee",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中央纪律检查委员会",
    en: "Central Commission for Discipline Inspection",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中央全面深化改革委员会",
    en: "Commission for Further Reform",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中央网络安全和信息化委员会",
    en: "Central Cyberspace Affairs Commission",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中央财经委员会",
    en: "Commission for Financial and Economic Affairs",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中央外事工作委员会",
    en: "Commission for Foreign Affairs",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中央机构编制委员会",
    en: "State Commission for Public Sector Reform",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中央国家安全委员会",
    en: "Commission for National Security",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中央军民融合发展委员会",
    en: "Commission for Integrated Civil-military Development",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中央全面依法治国委员会",
    en: "Commission for Law-based Governance",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中央审计委员会",
    en: "Auditing Commission",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中央金融委员会",
    en: "Financial Commission",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中央科技委员会",
    en: "Commission for Science and Technology",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中央教育工作领导小组",
    en: "Central Leading Group for Education",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "全国人民代表大会",
    en: "National People's Congress(NPC)",
    enAlt: ["NPC"],
    zhAlt: [],
  },
  {
    zh: "全国人民代表大会常务委员会",
    en: "Standing Committee of the National People's Congress",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "全国人民代表大会主席团",
    en: "Presidium of the National People's Congress",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "全国人民代表大会各专门委员会",
    en: "Special Committees of the NPC",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国国务院办公厅",
    en: "General Office of the State Council of the People's Republic of China",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国外交部",
    en: "Ministry of Foreign Affairs of the People's Republic of China",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国国防部",
    en: "Ministry of National Defense of the People's Republic of China",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国国家发展和改革委员会",
    en: "National Development and Reform Commission(NDRC)",
    enAlt: ["NDRC"],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国教育部",
    en: "Ministry of Education of the People's Republic of China",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国科学技术部",
    en: "Ministry of Science and Technology of the People's Republic of China",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国工业和信息化部",
    en: "Ministry of Industry and Information Technology",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国国家民族事务委员会",
    en: "State Ethnic Affairs Commission of the People's Republic of China",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国公安部",
    en: "Ministry of Public Security of the People's Republic of China",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国国家安全部",
    en: "Ministry of State Security of the People's Republic of China",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国民政部",
    en: "Ministry of Civil Affairs of the People's Republic of China",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国司法部",
    en: "Ministry of Justice of the People's Republic of China",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国财政部",
    en: "Ministry of Finance of the People's Republic of China",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国人力资源和社会保障部",
    en: "Ministry of Human Resources and Social Security",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国自然资源部",
    en: "Ministry of Natural Resources",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国生态环境部",
    en: "Ministry of Ecology and Environment",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国住房和城乡建设部",
    en: "Ministry of Housing and Urban-Rural Development",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国交通运输部",
    en: "Ministry of Transport",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国水利部",
    en: "Ministry of Water Resources of the People's Republic of China",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国农业农村部",
    en: "Ministry of Agriculture and Rural Affairs",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国商务部",
    en: "Ministry of Commerce",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国文化和旅游部",
    en: "Ministry of Culture and Tourism",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国国家卫生健康委员会",
    en: "National Health Commission",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国退役军人事务部",
    en: "Ministry of Veterans Affairs",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国应急管理部",
    en: "Ministry of Emergency Management",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中国人民银行",
    en: "People's Bank of China",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国审计署",
    en: "National Audit Office of the People's Republic of China",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "国务院国有资产监督管理委员会",
    en: "State-owned Assets Supervision and Administration Commission of the State Council(SASAC)",
    enAlt: ["SASAC"],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国海关总署",
    en: "General Administration of Customs of the People's Republic of China",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "国家税务总局",
    en: "State Administration of Taxation",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "国家市场监督管理总局",
    en: "State Administration for Market Regulation",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "国家金融监督管理总局",
    en: "National Financial Regulatory Administration",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "国家体育总局",
    en: "General Administration of Sport of China",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "国家国际发展合作署",
    en: "China International Development Cooperation Agency",
    enAlt: ["China International Development Co-operation Agency"],
    zhAlt: [],
  },
  {
    zh: "国家广播电视总局",
    en: "National Radio and Television Administration",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "国务院研究室",
    en: "State Council Research Office",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "国务院港澳事务办公室",
    en: "Hong Kong and Macao Affairs Office of the State Council",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "新华通讯社",
    en: "Xinhua News Agency",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中国科学院",
    en: "Chinese Academy of Sciences",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中国社会科学院",
    en: "Chinese Academy of Social Sciences",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中国工程院",
    en: "Chinese Academy of Engineering",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "国务院发展研究中心",
    en: "Development Research Centre of the State Council",
    enAlt: ["Development Research Center of the State Council"],
    zhAlt: [],
  },
  {
    zh: "中国人民政治协商会议",
    en: "Chinese People's Political Consultative Conference(CPPCC)",
    enAlt: ["CPPCC"],
    zhAlt: [],
  },
  {
    zh: "中国人民政治协商会议全国委员会",
    en: "National Committee of the Chinese People's Political Consultative Conference(NCCPPCC)",
    enAlt: ["NCCPPCC"],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国最高人民法院",
    en: "The Supreme People's Court of the People's Republic of China(SPC)",
    enAlt: ["SPC"],
    zhAlt: [],
  },
  {
    zh: "中华人民共和国最高人民检察院",
    en: "The Supreme People's Procuratorate of the People's Republic of China(SPP)",
    enAlt: ["SPP"],
    zhAlt: [],
  },
  {
    zh: "高级人民法院",
    en: "Higher People's Court",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "中级人民法院",
    en: "Intermediate People's Court",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "基层人民法院",
    en: "Primary People's Court",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "省人民政府",
    en: "Provincial People's Government",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "自治区人民政府",
    en: "Autonomous Region People's Government",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "直辖市人民政府",
    en: "Municipal People's Government",
    enAlt: [],
    zhAlt: ["设区的市人民政府"],
  },
  {
    zh: "设区的市人民政府",
    en: "Municipal People's Government",
    enAlt: [],
    zhAlt: ["直辖市人民政府"],
  },
  {
    zh: "自治州人民政府",
    en: "Autonomous Prefecture People's Government",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "县人民政府",
    en: "County People's Government",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "市辖区人民政府",
    en: "District People's Government",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "县级市人民政府",
    en: "County-level City People's Government",
    enAlt: [],
    zhAlt: [],
  },
  {
    zh: "乡（镇）人民政府",
    en: "Township People's Government",
    enAlt: [],
    zhAlt: [],
  },
]
