/**
 * 文章库 · 真题与样题（**自动生成，不要手改**）。
 *
 * 生成命令：node scripts/build-exams.mjs --write
 * 材料：仓库里的 `exams-src/*.json`——从「国才杯」笔译历年真题与官方样题里**人工整理**出来的
 *      原文与官方参考译文（卷头、题号、答题框、评分标准都剔除了；这一步没法机械化，
 *      因此材料以 json 的形式进仓库，可复核、可重算）。
 *      原始文件来自：桌面\下载\【2026】外研社（国才杯）笔译赛项\【2023-2026】笔译历年真题（校赛、初赛、省赛）
 *      与同级的\【2023-2026】笔译（官方）样题，每篇的 `title` 末尾都写着它的来源文件。
 *
 * 每篇的字段见 domain/articles.ts 的 Article。五条约定与文章库一致：
 *   1. 正文与参考译文都是**全文**，段落之间留一个空行；两边段数**完全一致**（脚本强校验）。
 *   2. **原文逐字照录**，不改写不润色；抽取造成的错字订正记在 exams-src 的 notes 里。
 *   3. **参考译文只来自官方答案**，没有答案的篇目 reference 是空串——绝不自己翻译。
 *   4. `units` 与文章库同一套口径：英译中数词，中译英数非空白字符。
 *   5. `title` 由零件拼出来，格式是「真题 2025 省赛 经济领域 | 简要概括的内容」：
 *      卷子层给 year / stage，篇目层给 topic（社会/经济/文化/生态/科技）与 summary。
 *      想改标题就改那两个字段，别改这个生成文件。*/

import type { Article } from '../articles'

export const EXAM_ARTICLES: readonly Article[] = [
  {
    id: "art-past-paper-en-to-zh-1",
    domain: "past-paper",
    direction: "en-to-zh",
    batch: 1,
    title: "真题 2024 省赛 生态领域 | 全球能源系统转型",
    units: 401,
    text: "A profound and systemic transformation of the global energy system must be achieved within 30 years. This condensed timeframe necessitates a strategic shift that expands beyond the focus on decarbonization of energy supply and energy consumption, toward designing an energy system that not only reduces carbon emissions but also supports a resilient and inclusive global economy. As a result, planning needs to extend beyond borders and the narrow confines of fuels to focus on the requirements of the new energy system and the economies it will sustain\n\nFocusing on the enablers of a renewables-dominated system can help address the structural barriers that hinder progress in the energy transition. Pursuing fuel and sectoral mitigation measures is necessary, but is insufficient to transition to an energy system fit for the dominance of renewables. From energy production and transportation to processing coal, oil and gas, the global infrastructure dedicated to energy will need to change. This will have impacts on power generation, industrial production and manufacturing, as well as on rail pipelines, and other means of supplying fossil fuels. Enhancing the focus on systems design will help accelerate the development of a new energy infrastructure and sustain its implementation\n\nGovernments can proactively shape a renewables-based energy system, overcome the flaws and inefficiencies of current structures, and more effectively influence outcomes. The simultaneous proactive shaping of physical, policy, and institutional structures will be essential to realizing development and climate objectives and achieving a more resilient and equitable world. These underpinnings should form the pillars of a structure that supports the energy transition\n\nPolicy and regulatory enablers must systematically prioritize the acceleration of the energy transition and a reduction in the role of fossil fuels. Today, the underlying policy and regulatory systems remain shaped around fossil fuels. While it is inevitable that fossil fuels will remain in the energy mix for some time, their share must dramatically decrease as we approach mid-century. Policy frameworks and markets should therefore focus on accelerating the transition and provide the essential underpinnings for a resilient and inclusive system.\n\nA well-skilled workforce is a lynchpin of a successful energy transition. A broad range of occupational profiles will be needed. Filling these jobs will require concerted action in education and skills building, and governments have a critical role in coordinating efforts to align the offerings of the education sector with projected industry needs-—whether in the form of vocational training or university courses",
    reference: "在未来30 年内，全球能源系统必须实现深刻且系统性的转型。这一紧迫的时间框架要求战略视角的拓展，不再局限于能源供应和消费的脱碳化，而是着眼于构建一个既能减少碳排放、又能支持全球经济韧性与包容性的能源系统。因此，规划应超越国界与燃料的狭隘限制，聚焦于新型能源系统及其所支撑经济的实际需求。\n\n聚焦于支持以可再生能源为主导的系统转型，有助于解决阻碍能源转型的结构性障碍。尽管燃料和行业的减排措施是必不可少的，但仅靠这些还不足以推动适应可再生能源主导的能源系统的转型。从能源生产、运输到煤炭、石油和天然气的加工，全球现有的能源基础设施将需要进行深层次的变革。这将影响发电、工业生产与制造业，以及铁路、管道等化石燃料的供应方式。加强对系统设计的重视，将有助于加速新型能源基础设施的开发，并支持其持续实施。\n\n各国政府可以主动引导基于可再生能源的能源系统建设，克服现有结构的缺陷和低效，从而更有效地影响最终成果。同步推动物理结构、政策框架和制度体系的变革，将是实现发展与气候目标、构建更具韧性和公平性的世界的关键。这些基础要素应当构成支撑能源转型的坚实支柱。\n\n政策和监管的推动力量必须系统性地优先加速能源转型，减少化石燃料的比重。当前的政策和监管体系仍主要围绕化石燃料而构建。尽管在未来一段时间内化石燃料仍将是能源结构的一部分，但随着本世纪中叶的临近，其比例必须大幅下降。因此，政策框架与市场应集中力量加速这一转型，为构建一个具有韧性和包容性的能源系统提供坚实的基础支撑。\n\n一支高技能劳动力队伍是推动能源转型成功的关键支柱。实现这一目标将需要多种职业类型的人才。要满足这些岗位的需求，教育和技能培训方面的协同行动势在必行，政府在其中起着至关重要的协调作用，以确保教育部门的课程设置与行业未来需求相一致——无论是职业培训还是高等教育课程。",
  },
  {
    id: "art-sample-en-to-zh-1",
    domain: "sample",
    direction: "en-to-zh",
    batch: 1,
    title: "样题 2024 社会领域 | 国际体育促进发展与和平日",
    units: 270,
    text: "The International Day of Sport for Development and Peace (IDSDP), which takes place annually on April 6, presents an opportunity to recognize the positive role sport and physical activity play in communities and in people’s lives across the globe.\n\nThe global theme for 2024 is “Sport for the Promotion of Peaceful and Inclusive Societies”.\n\nIn observance of the International Day, on April 4 an event at UN Headquarters in New York will focus on how prominent sporting bodies engage in partnerships to make positive impacts for people and the environments in which they operate. It will bring together members of the international sporting community — including members of the United Nations Football for the Goals initiative — to share best practices, discuss challenges, and explore collaborative opportunities to drive positive social change and contribute to global efforts towards sustainable development and peace.\n\nThe United Nations has long recognized the power and universality of sport, using it to unite individuals and groups through supporting sport for development efforts, participating in events from the global to the grassroots level, and developing its own sports-related campaigns and initiatives.\n\nSport has proven to be a cost-effective and flexible tool in promoting peace and development objectives. In the 2030 Agenda for Sustainable Development sport’s role for social progress is further acknowledged. Sport is also an important enabler of sustainable development. We recognize the growing contribution of sport to the realization of development and peace in its promotion of tolerance and respect and the contributions it makes to the empowerment of women and of young people, individuals and communities as well as to health, education and social inclusion",
    reference: "每年的 4 月 6 日，国际体育促进发展与和平日（IDSDP）为我们提供了一个机会，让我们认识到体育和身体活动在全球社区和人们生活中所发挥的积极作用。\n\n2024 年的全球主题是“体育促进和平与包容性社会”。\n\n为纪念国际体育促进发展与和平日，4 月 4 日，纽约联合国总部将举行一场活动，重点讨论著名体育机构如何通过合作伙伴关系对人们和他们所处的环境产生积极影响。活动将汇集国际体育界的成员，包括联合国“足球促进目标”倡议的成员，共同分享最佳实践，讨论挑战，并探索合作机会，以推动积极的社会变革，助力全球可持续发展与和平的努力。\n\n联合国长期以来一直认识到体育的力量和普遍性，通过支持体育促进发展的努力，参与从全球到基层的各种活动，开展自身的体育相关活动和倡议，来团结个人和群体。\n\n体育已被证明是一个在促进和平与发展目标方面具有成本效益和灵活性的工具。在《2030 年可持续发展议程》中，体育在社会进步中的作用得到了进一步认可。体育也是可持续发展的重要推动者。我们认识到体育在推广宽容与尊重、促进妇女和年轻人的赋权、个人和社区的赋权以及健康、教育和社会包容目标方面对发展与和平实现的日益重要的贡献。",
  },
  {
    id: "art-past-paper-en-to-zh-2",
    domain: "past-paper",
    direction: "en-to-zh",
    batch: 2,
    title: "真题 2024 省赛 生态领域 | 海平面上升与气候理想社区",
    units: 382,
    text: "Sea levels are changing rapidly and could rise by 1 metre or more by 2100 without drastic reductions in greenhouse-gas emissions. Low-lying coastal areas-home to nearly one billion people are at high risk of erosion and flooding. In July, for example, torrential rain, coupled with high tides and worsening erosion, inundated coastal areas in Lagos（拉各斯), flooding around2, 000 properties and displacing residents across the Nigerian metropolis.\n\nFor coastal communities, urban planning and smart technologies are key to climate adaptation and mitigation. Futuristic designs for flood-resilient settlements or \"climatopias\", are gaining popularity especially in areas projected to be underwater in a few decades. These large infrastructure projects are being touted by governments and developers as tools to expand the availability of housing, reduce pressures on land, enhance energy efficiency, promote eco- friendly transportation and lessen the effects of flooding.\n\nCritics view them as technological fantasies aimed at growing the value of the property market near oceans and rivers. They also note that climatopias could stifle sustainable adaptations- and we agree that this is a real concern. With the right approach, however, they can be made viable. It is crucial that governments, scientists, environmentalists, think tanks, local communities and ocean-governing agencies evaluate the challenges and benefits of these projects in the short and long term to determine their legitimacy as climate solutions.\n\nHere we offer six criteria by which to assess climatopias during their planning and implementation stages: design type, practicality, ecosystem effects, maladaptation risk, justice concerns and regulatory frameworks.\n\nFor design type, unlike the infrastructure in such traditional communities, climatopias are designed to be high-tech cities equipped with solar panels for generating electricity, deep-sea cooling systems, health-care centres, schools, recreational areas and businesses. There are three major ways in which developers are converting ocean and near-shore areas into habitable spaces: reclaimed land, amphibious houses, and floating cities.\n\nIn terms of practicality, planners, engineers and environmental specialists must assess the construction materials, structural integrity, safety, cost, market demand and financial sustainability of climatopia projects. Besides, all climatopias are vulnerable to extreme weather- from storms and tsunamis to hurricane-induced floodings--with significant risks of damage and loss of life. To address these problems, governments, planners, insurance companies and affected communities must work together to set industry standards as well as design early-warning systems and evacuation procedures.",
    reference: "海平面正在迅速上升，如果不大幅减少温室气体排放，到2100 年，海平面可能会上升1 米甚至更多。低洼的沿海地区——居住着近十亿人口—正面临严重的侵蚀和洪水风险。例如，今年7 月，倾盆大雨与高潮潮位及日益加剧的海岸侵蚀共同作用，淹没了拉各斯(Lagos) 沿海区域，约2000 处房屋遭遇洪水，迫使这座尼日利亚大都市的居民流离失所。\n\n对于沿海社区而言，城市规划和智能技术是应对和缓解气候变化的关键。具有防洪能力的未来社区设计，或称为“气候理想社区”(climatopias)，在未来可能被海水淹没的区域越来越受青睐。这些大型基础设施项目被政府和开发商视为扩展住房供应、缓解土地压力、提升能源效率、推动环保交通并减少洪水影响的有效方案。\n\n批评者认为，这些项目是以提升滨海及河岸地段房地产市场价值为目的的技术幻想。他们还指出，气候理想社区可能会抑制可持续的适应措施—而我们也认为这是一个真实的担忧。然而，采用正确的方法，这些项目可以变得切实可行。政府、科学家、环保人士、智库、当地社区和海洋管理机构应当共同评估这些项目在短期和长期内的挑战与益处，以确定它们作为气候解决方案的合法性。\n\n我们提出了六项标准，以用于在气候理想社区的规划和实施阶段进行评估：设计类型、实用性、生态系统影响、不良适应风险、公平性问题以及监管框架。\n\n在设计方面，与传统社区基础设施不同，气候理想社区被构想为高科技城市，配备太阳能发电系统、深海冷却系统、医疗中心、学校、娱乐区域和商业设施。开发商主要通过填海造地、两栖房屋和浮动城市三种方式，将海洋和近岸区域转变为可居住空间。\n\n在实用性方面，规划者、工程师和环境专家必须评估气候理想社区项目的建材选择、结构完整性、安全性、成本、市场需求以及财务可持续性。此外，所有气候理想社区都易受极端天气的威胁——从风暴、海啸到飓风引发的洪水——面临严重的损害和生命风险。为应对这些挑战，政府、规划者、保险公司和受影响的社区必须密切合作，制定行业标准，并设计预警系统和疏散方案。",
  },
  {
    id: "art-sample-en-to-zh-2",
    domain: "sample",
    direction: "en-to-zh",
    batch: 2,
    title: "样题 2025 社会领域 | 国际体育促进发展与和平日（2024 年主题）",
    units: 271,
    text: "The International Day of Sport for Development and Peace (IDSDP), which takes place annually on April 6, presents an opportunity to recognize the positive role sport and physical activity play in communities and in people’s lives across the globe.\n\nThe global theme for 2024 is “Sport for the Promotion of Peaceful and Inclusive Societies”.\n\nIn observance of the International Day, on April 4 an event at UN Headquarters in New York will focus on how prominent sporting bodies engage in partnerships to make positive impacts for people and the environments in which they operate. It will bring together members of the international sporting community — including members of the United Nations Football for the Goals initiative — to share best practices, discuss challenges, and explore collaborative opportunities to drive positive social change and contribute to global efforts towards sustainable development and peace.\n\nThe United Nations has long recognized the power and universality of sport, using it to unite individuals and groups through supporting sport for development efforts, participating in events from the global to the grassroots level, and developing its own sports-related campaigns and initiatives.\n\nSport has proven to be a cost-effective and flexible tool in promoting peace and development objectives. In the 2030 Agenda for Sustainable Development sport’s role for social progress is further acknowledged. Sport is also an important enabler of sustainable development. We recognize the growing contribution of sport to the realization of development and peace in its promotion of tolerance and respect and the contributions it makes to the empowerment of women and of young people, individuals and communities as well as to health, education and social inclusion objectives.",
    reference: "",
  },
  {
    id: "art-past-paper-en-to-zh-3",
    domain: "past-paper",
    direction: "en-to-zh",
    batch: 3,
    title: "真题 2024 校赛 社会领域 | 英法领导人会晤",
    units: 210,
    text: "The Prime Minister of the United Kingdom of Great Britain and Northern Ireland and the President of the French Republic met today at Blenheim Palace. In this, the 120th anniversary year of the Entente Cordiale, the two leaders discussed the full spectrum of the bilateral relationship between the UK and France, the UK's intention to reset its relationship with the EU and wider Europe, as well as international and global issues. 80 years on from the D-Day landings and the Liberation of France the leaders remembered the immense common sacrifices that both countries have made to defend their shared values and to protect their societies. And 30 years on from the opening of the Channel Tunnel they recalled what the UK and France can build together when they do not constrain their ambitions, allowing their economies to flourish and their people to connect.\n\nAs fellow members of the G7, G20, NATO and permanent members of the UN Security Council, the UK and France will continue to work together to provide global leadership in an era of renewed geopolitical instability. They are committed to continuing to invest in the European Political Community format to bring together Europe's democracies and contribute to regional stability and security through political dialogue and concrete cooperation.",
    reference: "英国首相与法国总统今天在布伦海姆宫会晤。在英法协约120 周年之际，两位领导人讨论了英法双边关系的各个方面、英国重置与欧盟及更广泛欧洲关系的意图，以及国际问题。在诺曼底登陆和解放法国80 周年之际，两位领导人回顾了两国为捍卫共同价值观和保护社会所作出的巨大牺牲。在英法开通海峡隧道30 周年之际，他们回想起两国曾经怀着远大抱负共同构建美好未来，推动经济繁荣和人民交流。\n\n作为七国集团(G7)、二十国集团(G7)、北约(NATO) 成员以及联合国安理会常任理事国，英法将继续携手在地缘政治不稳定的新时期提供全球领导。双方承诺继续投资欧洲政治共同体，团结欧洲的民主国家，通过政治对话和具体合作促进地区稳定与安全。",
  },
  {
    id: "art-sample-en-to-zh-3",
    domain: "sample",
    direction: "en-to-zh",
    batch: 3,
    title: "样题 2026 社会领域 | 国际体育促进发展与和平日",
    units: 269,
    text: "The International Day of Sport for Development and Peace (IDSDP), which takes place annually on April 6, presents an opportunity to recognize the positive role sport and physical activity play in communities and in people’s lives across the globe.\n\nThe global theme for 2024 is “Sport for the Promotion of Peaceful and Inclusive Societies”.\n\nIn observance of the International Day, on April 4 an event at UN Headquarters in New York will focus on how prominent sporting bodies engage in partnerships to make positive impacts for people and the environments in which they operate. It will bring together members of the international sporting community—including members of the United Nations Football for the Goals initiative—to share best practices, discuss challenges, and explore collaborative opportunities to drive positive social change and contribute to global efforts towards sustainable development and peace.\n\nThe United Nations has long recognized the power and universality of sport, using it to unite individuals and groups through supporting sport for development efforts, participating in events from the global to the grassroots level, and developing its own sports-related campaigns and initiatives.\n\nSport has proven to be a cost-effective and flexible tool in promoting peace and development objectives. In the 2030 Agenda for Sustainable Development sport’s role for social progress is further acknowledged. Sport is also an important enabler of sustainable development. We recognize the growing contribution of sport to the realization of development and peace in its promotion of tolerance and respect and the contributions it makes to the empowerment of women and of young people, individuals and communities as well as to health, education and social inclusion objectives.",
    reference: "",
  },
  {
    id: "art-past-paper-en-to-zh-4",
    domain: "past-paper",
    direction: "en-to-zh",
    batch: 4,
    title: "真题 2024 校赛 经济领域 | 主流经济学与新自由主义",
    units: 279,
    text: "In recent decades, mainstream economics has become closely associated with a particular set of policies labeled“neoliberalism.” The neoliberal policy paradigm favors expanding the scope of markets(including global markets) and restricting the role of government action. Today it is widely recognized that this approach failed in a number of important respects. It widened inequality within nations, did little to promote the climate transition, and created blind spots ranging from global public health to supply-chain resilience.\n\nThe neoliberal era did witness a major achievement. Record economic growth in many developing economies, including the most populous, brought a massive reduction in extreme poverty around the world. Yet the countries that did best during this period, such as China, hardly subscribed to neoliberal rules. They relied on industrial policies, state enterprises, and capital controls as much as they did on freer markets. Meanwhile, the performance of countries that adhered most closely to the neoliberal playbook, such as Mexico, was abysmal.\n\nWas economics responsible for neoliberalism? Most of us know that economics is a way of thinking rather than a set of policy recommendations. The tools of contemporary economics yield very few generalizations that offer immediate policy guidance. First-order principles—— such as thinking at the margin, aligning private incentives with social costs and benefits, fiscal sustainability, and sound money—— are essentially abstract ideas that do not map into unique remedies.\n\nChina itself offers the best illustration of the plasticity of economic principles. Few would dispute that the Chinese government took advantage of markets, private incentives, and globalization. Yet it did so through unconventional innovations — — the household responsibility system, dual-track pricing, township-and-village enterprises, special economic zones—— that would be unrecognizable in standard Western policy recommendations.",
    reference: "",
  },
  {
    id: "art-past-paper-en-to-zh-5",
    domain: "past-paper",
    direction: "en-to-zh",
    batch: 5,
    title: "真题 2025 初赛 经济领域 | 贸易政策紧张与关税的作用机制",
    units: 300,
    text: "Trade policy tensions are escalating fast. In recent months, several large economies have announced or implemented sweeping new tariffs, reviving a policy tool that many thought to have been largely relegated to the past. These developments have sparked a flurry of political commentary—but behind the headlines, there exists a body of economic research that helps to make sense of what tariffs actually do.\n\nAt their core, tariffs are simple: They raise the domestic price of imported goods. But their effects ripple through the economy in complex ways—altering prices, wages, exchange rates and trade patterns. As governments revisit this powerful lever, understanding the economic mechanisms at play has never been more important.\n\nAt the most basic level, a tariff is a tax on imported products. It drives a wedge between the world price and the domestic price. For instance, if a 10 percent tariff is imposed on a product with a world price of US$100, the domestic price becomes US$110. The difference—US$10—is collected as tariff revenue, which the government can use to finance its expenditures.\n\nTariffs can also affect the world price of a product, particularly when they are imposed by a large economy. The logic is that higher domestic prices reduce domestic demand, which in turn lowers world demand, and thus world prices. In our example, the world price might fall to 95 after the tariff is imposed, resulting in a domestic price of 104.50. In this case, part of the tariff is effectively paid by foreign producers.\n\nThis cost-shifting creates incentives for large economies to unilaterally impose tariffs. However, this so-called optimal tariff argument overlooks the possibility of retaliation. If country A imposes tariffs on country B, country B has an incentive to respond in kind. The end result is a trade war that leaves both sides worse off.",
    reference: "贸易政策紧张局势正在迅速升级。近几个月来，几个大型经济体宣布或实施了大规模新关税，让一种许多人认为已基本成为历史的政策工具重出江湖。这些发展引发了大量政治评论——但在头条新闻背后，有一系列经济研究有助于弄清楚关税实际上起到的作用。\n\n关税的核心很简单：它们提高进口商品的国内价格。但其影响以复杂的方式在经济中蔓延——改变价格、工资、汇率和贸易模式。随着各国政府重新审视这一有力手段，理解其背后的经济机制变得尤为重要。\n\n从最基本层面看，关税是对进口产品征收的税。它在世界价格和国内价格之间造成差异。例如，对一种世界价格为100美元的产品征收10%的关税，国内价格就会变成110美元。两者的差额——10美元——会作为关税收入被征收，政府可将其用于为支出提供资金。\n\n关税也会影响产品的世界价格，尤其是当由大型经济体征收时。逻辑是，国内价格提高会减少国内需求，进而降低世界需求，从而拉低世界价格。在我们的例子中，征收关税后世界价格可能降至95美元，国内价格则变为104.50美元。在这种情况下，部分关税实际上由外国生产商支付。\n\n这种成本转移促使大型经济体有动力单方面征收关税。然而，这种所谓的最优关税论点忽视了报复的可能性。如果A国对B国征收关税，B国有动力以牙还牙。最终结果是贸易战，让双方都受损。",
  },
  {
    id: "art-past-paper-en-to-zh-6",
    domain: "past-paper",
    direction: "en-to-zh",
    batch: 6,
    title: "真题 2026 公开赛 生态领域 | 固体垃圾管理与循环经济",
    units: 287,
    text: "The world is at a critical juncture in managing its growing waste. Rapid population growth, accelerating urbanization, rising incomes, and increased consumption are driving a surge in municipal solid waste generation that is outpacing the capacity of local systems and municipal budgets. As a result, cities and communities worldwide are struggling to keep up with mounting quantities of waste. When waste is not managed well, the consequences are far reaching: environmental pollution intensifies, greenhouse gas emissions rise, and valuable natural resources are wasted. These threaten public health and the environment and undermine economic development and the livability of cities.\n\nYet, within the crises lies an opportunity. By investing in more efficient, inclusive, and sustainable waste management systems, countries can unlock new avenues for economic growth, job creation, and innovation. Improved waste management systems that embrace circular economy principles, where materials are reused and value is retained, can transform waste from a burden into a driver of sustainable development, benefiting both local communities and the global environment.\n\nSolid waste management lies at the nexus of local service delivery, livability, and economic development, and is increasingly central to global environmental sustainability. At the local level, it is essential to public health, environmental quality, climate resilience, and the functioning of cities. Effective, reliable, and inclusive waste services reduce the spread of disease, prevent contamination of water, soil, and air, mitigate flooding caused by blocked drainage, and support a safe, dignified urban environment.\n\nClean cities contribute to local economic development by enhancing competitiveness and strengthening the overall business environment. As cities transition toward more circular economies, where waste-derived materials are reintegrated into productive use, solid waste management is firmly established as a driver of investment, private sector participation, and job creation.",
    reference: "世界正处于应对日益增长的垃圾问题的关键时刻。人口快速增长、城市化加速、收入水平上升以及消费增加，正在推动城市固体垃圾产生量的急剧上升，这一增长速度已经超过了地方系统和市政预算的承载能力。因此，全球各地的城市和社区都在努力应对不断增加的垃圾数量。如果垃圾管理不当，其后果将十分严重：环境污染加剧、温室气体排放上升、宝贵的自然资源被浪费。这些问题威胁着公共健康和环境安全，同时破坏经济发展和城市宜居性。\n\n然而，危机之中也蕴含机遇。通过投资建设更高效、包容且可持续的垃圾管理系统，各国可以开辟新的经济增长、就业创造和创新途径。改进后的垃圾管理系统如果遵循循环经济原则，使材料得到重复利用并保留价值，就能够将垃圾从负担转变为可持续发展的推动力，从而惠及地方社区和全球环境。\n\n固体垃圾管理处于地方服务提供、城市宜居性和经济发展交汇的关键位置，并日益成为全球环境可持续性的核心。在地方层面，它对于公共健康、环境质量、气候韧性以及城市运作至关重要。有效、可靠且包容的垃圾管理服务可以减少疾病传播、防止水体、土壤和空气污染、缓解因排水堵塞引起的洪涝，并支持一个安全、有尊严的城市环境。\n\n清洁的城市有助于地方经济发展，通过提升竞争力和增强整体营商环境实现。随着城市向更加循环的经济模式转型，将垃圾衍生材料重新纳入生产性使用，固体垃圾管理已经牢固确立为吸引投资、促进私营部门参与和创造就业的重要驱动力。",
  },
  {
    id: "art-past-paper-zh-to-en-1",
    domain: "past-paper",
    direction: "zh-to-en",
    batch: 1,
    title: "真题 2023 文化领域 | 端午节习俗与传统节日文化传承",
    units: 228,
    text: "又是一年端阳至，人们吃粽子、饮雄黄、插艾草、戴香囊、划龙舟、荡秋千，在丰富多彩的活动中品读传统文化、过好传统佳节。作为率先入选联合国教科文组织非物质文化遗产名录的中国传统节日，端午节承载着多样且厚重的传统文化，需要进一步挖掘。除了参与体验端午节日的仪式感，更重要的是，要讲好传统节日故事。一些地方通过开展端午诗会、专题展览、读书分享会等活动，借助动漫、情景剧、纪录片等形式，培育天人合一的自然观、除秽驱病的健康观，已成为传承发扬传统节日文化精髓的创新途径。",
    reference: "The Dragon Boat Festival has arrived. Eating zongzi, drinking xionghuang wine, hanging mugwort leaves, wearing perfume pouches, enjoying dragon boat races and swings—the Chinese people are celebrating this traditional festival by immersing themselves in various traditional cultural activities. As the first traditional Chinese festival to be inscribed on the List of Intangible Cultural Heritage by UNESCO, the Dragon Boat Festival is representative of China's diverse and profound traditional culture that calls for further promotion. In addition to experiencing the ceremonial aspects of the Dragon Boat Festival, it is also important for us to tell the stories of the traditional festival well. To this end, some cities are holding events such as poetry recitals, theme exhibitions, and book readings; artists are also telling stories by means of animation, sitcoms and documentaries. These efforts advocate harmony between humans and nature and raise awareness for preventing disease and maintaining health. They are creative means to pass on and promote the cultural essence of traditional festivals.",
  },
  {
    id: "art-sample-zh-to-en-1",
    domain: "sample",
    direction: "zh-to-en",
    batch: 1,
    title: "样题 2023 科技领域 | 国家速滑馆与「冰丝带」",
    units: 328,
    text: "国家速滑馆是北京 2022 年冬奥会的标志性建筑，其场馆施工从 2018 年 1 月持续到 2020 年 12 月，拥有亚洲最大的全冰面设计，冰面面积达到了 1.2 万平方米。在冬奥会期间，国家速滑馆将承担速度滑冰项目的比赛和训练。冬奥会后，该馆将成为能够举办滑冰、冰球等国际赛事及大众进行冰上活动的多功能场馆。\n\n国家速滑馆因其造型设计又被称为“冰丝带”，其设计理念来自一个冰和速度结合的创意，22 条丝带就像运动员滑过的痕迹，象征速度和激情。在自然界中，冰的感觉透明、寒冷而且坚硬，但是在特定的气候条件下，冰会由缝隙的毛细作用而呈现丝带一样的形态。建筑设计具有刚柔并济的力量：水成为立方，冰也可以成为丝带。冰和速度结合，立面的设计概念称为“冰丝带”，呈现动感、轻盈、透明的建筑效果。",
    reference: "",
  },
  {
    id: "art-past-paper-zh-to-en-2",
    domain: "past-paper",
    direction: "zh-to-en",
    batch: 2,
    title: "真题 2023 经济领域 | 2023 年前 4 个月外贸进出口形势",
    units: 293,
    text: "海关总署发布的数据显示，2023年前4个月，我国进出口总值13.32万亿元，同比增长5.8%，进出口延续了向好态势。外贸进出口展现出较强韧性，为全年实现外贸促稳提质打下了基础。值得一提的是，今年前4个月，有进出口实绩的民营企业数量同比增加了8.9%，为拓宽就业渠道、稳定就业大盘发挥了积极作用。\n\n外贸平稳向好，得益于我国产业链水平不断提升。高技术、高附加值、引领绿色转型的产品领跑出口，表明我国外贸新动能不断培育壮大，更折射出供给侧结构性改革下，中国制造业迈向高端化、智能化、绿色化的坚实足迹。依靠科技创新与低碳转型，“中国制造”不断塑造和积累国际竞争新优势，中国经济高质量发展活力强劲。",
    reference: "According to data released by the General Administration of Customs, China’s import and export value reached 13.32 trillion yuan in the first four months of 2023, showing a year-on-year increase of 5.8%. This steady growth in imports and exports reflects the resilience of China’s foreign trade and lays a solid foundation for stabilizing and improving its quality throughout the year. Notably, the number of private enterprises with tangible import and export results increased by 8.9% compared to the same period last year, contributing to the expansion of employment opportunities and the stability of the job market.\n\nThe steady improvement in foreign trade can be attributed to the continuous development of China’s industrial chain. Leading the export market with high-tech, high-added-value, and green transformation-driven products signifies the ongoing cultivation and growth of China’s foreign trade. It also reflects the firm steps taken by China’s manufacturing industry towards high-end, smarter, and greener production under the supply-side structural reform. Through scientific and technological innovation and low-carbon transition, “Made in China” is constantly shaping and accumulating new advantages in international competition, thereby providing strong impetus for the high-quality development of China’s economy.",
  },
  {
    id: "art-sample-zh-to-en-2",
    domain: "sample",
    direction: "zh-to-en",
    batch: 2,
    title: "样题 2023 文化领域 | 柯灵《乡土情结》节选",
    units: 496,
    text: "每个人的心里，都有一方魂牵梦萦的土地。得意时想到它，失意时想到它。逢年逢节，触景生情，随时随地想到它。海天茫茫，风尘碌碌，酒阑灯灺人散后，良辰美景奈何天，洛阳秋风，巴山夜雨，都会情不自禁地惦念它。离得远了久了，使人愁肠百结：“客舍并州数十霜，归心日夜忆咸阳，无端又渡桑乾水，却望并州是故乡。”好不容易能回家了，偏又忐忑不安：“岭外音书断，经冬复历春。近乡情更怯，不敢问来人。”异乡人这三个字，听起来音色苍凉：“他乡遇故知”，则是人生一快。一个怯生生的船家女，偶尔在江上听到乡音，就不觉喜上眉梢，顾不得娇羞，和隔船的陌生男子搭讪：“君家何处住？妾住在横塘。停船暂借问，或恐是同乡。”辽阔的空间，悠邈的时间，都不会使这种感情褪色：这就是乡土情结。\n\n人生旅途崎岖修远，起点站是童年。人第一眼看见的世界——几乎是世界的全部，就是生我育我的乡土。他开始感觉饥饱寒暖，发为悲啼笑乐。他从母亲的怀抱，父亲的眼神，亲族的逗弄中开始体会爱。但懂得爱的另一面——憎和恨，却须在稍稍接触人事以后。乡土的一山一水，一虫一鸟，一草一木，一星一月，一寒一暑，一时一俗，一丝一缕，一饮一啜，都溶化为童年生活的血肉，不可分割。",
    reference: "",
  },
  {
    id: "art-past-paper-zh-to-en-3",
    domain: "past-paper",
    direction: "zh-to-en",
    batch: 3,
    title: "真题 2024 省赛 文化领域 | 乡村旅游与文化内涵、生态保护",
    units: 363,
    text: "我国乡村旅游蓬勃发展，但也存在粗放式开发、创意不足等现象。发展乡村游，如何因地制宜？\n\n首先，要让乡村人气兴旺。有些乡村景区建成后，把有意愿、有能力的村民重新请回来。村民或布置民俗景观，或在景区开商铺，还有的经营民宿。村民回来了，才有了原汁原味的乡土民俗，才有了农家小院里的乡音小调，才有了土灶上烹饪的本土小菜。只有留住原住村民，才能真实展示当地风俗本色。\n\n此外，乡村游也需要文化内涵。有些村庄邀请本村和周边的手艺人、非遗传承人，将活态非遗融入传统村落风貌，为游客创造了体验传统文化的丰富载体，有效地增强了旅游吸引力同时，乡村旅游的可持续发展还需注重生态环境的保护。必须避免过度开发和破坏自然资源，确保绿水青山与经济效益并重。一些村庄推行生态农业、打造田园景观，结合农耕体验项目，在保留原生态环境的同时，提升了游客的参与感与互动性。",
    reference: "China's rural tourism is thriving, yet challenges such as unsustainable development and limited creativity remain. How can we develop rural tourism in a way that is responsive to the unique conditions of each area?\n\nTo truly revitalize rural communities, it is essential to bring back the people. In some rural tourist areas, once development is complete, willing and capable villagers are invited to return. These villagers may create traditional cultural displays, open shops, or operate homestays within the scenic area. With the return of the villagers, authentic rural customs and culture also come alive: local dialects echo through the courtyards, and native dishes are prepared on rustic stoves. Only by retaining the original residents can the true essence of local traditions be faithfully preserved and presented.\n\nMoreover, rural tourism should be enriched with cultural depth. Some villages invite local artisans and inheritors of intangible cultural heritage from the village and surrounding areas, weaving these living traditions into the fabric of the village's landscape. This creates meaningful opportunities for visitors to engage with traditional culture, greatly enhancing the appeal and allure of rural tourism. For rural tourism to develop sustainably, ecological conservation must remain a priority. Overdevelopment and the depletion of natural resources should be carefully avoided to strike a balance between preserving green landscapes and generating economic benefits. Some villages have adopted ecological farming, created idyllic landscapes, and introduced hands-on farming experiences, which not only protect the natural environment but also deepen visitor engagement and interaction.",
  },
  {
    id: "art-sample-zh-to-en-3",
    domain: "sample",
    direction: "zh-to-en",
    batch: 3,
    title: "样题 2024 经济领域 | 海关总署外贸数据",
    units: 293,
    text: "海关总署发布的数据显示，2023 年前 4 个月，我国进出口总值 13.32 万亿元，同比增长 5.8%，进出口延续了向好态势。外贸进出口展现出较强韧性，为全年实现外贸促稳提质打下了基础。值得一提的是，今年前 4 个月，有进出口实绩的民营企业数量同比增加了 8.9%，为拓宽就业渠道、稳定就业大盘发挥了积极作用。\n\n外贸平稳向好，得益于我国产业链水平不断提升。高技术、高附加值、引领绿色转型的产品领跑出口，表明我国外贸新动能不断培育壮大，更折射出供给侧结构性改革下，中国制造业迈向高端化、智能化、绿色化的坚实足迹。依靠科技创新与低碳转型，“中国制造”不断塑造和积累国际竞争新优势，中国经济高质量发展活力强劲。",
    reference: "According to data released by the General Administration of Customs, China's total import and export value in the first four months of 2023 was 13.32 trillion yuan, a year-on-year increase of 5.8%, continuing the positive trend in foreign trade. The strong resilience of foreign trade has laid a foundation for achieving the goal of stabilizing and improving the quality of foreign trade throughout the year. Notably, the number of private enterprises with actual import and export performance increased by 8.9% year-on-year in the first four months, playing a positive role in broadening employment channels and stabilizing the overall employment situation.\n\nThe steady and positive trend in foreign trade is attributed to the continuous improvement of China's industrial chain. High-tech, high-value-added products, and those leading the green transition have spearheaded exports, indicating the continuous growth of new driving forces in China's foreign trade. This also reflects the solid progress of China's manufacturing industry towards high-end, intelligent, and green development under supply-side structural reforms. Relying on technological innovation and low-carbon transition, \"Made in China\" continues to create and accumulate new international competitive advantages, demonstrating the strong",
  },
  {
    id: "art-past-paper-zh-to-en-4",
    domain: "past-paper",
    direction: "zh-to-en",
    batch: 4,
    title: "真题 2024 省赛 经济领域 | 服贸会与服务贸易高质量发展",
    units: 340,
    text: "服贸会(CIFTIS)是中国服务业和服务贸易高质量发展的生动写照。今年上半年，中国服务贸易规模创历史新高，服务进出口总额达3.6 万亿元，同比增长14%。中国正以高水平开放推动服务贸易高质量发展，为全球经济发展贡献更大动力。\n\n走进服贸会展区，数字化、智能化、绿色化气息扑面而来。应用人工智能深度学习技术的手术机器人，通过一张CT 片，就能帮医生制定个体化手术方案：电动无人机助力农业生产、巡检、消防提升效率...服贸会上，不少机构和企业首发新技术、新成果，引领行业创新趋势。\n\n作为服务贸易国际合作的重要平台，服贸会着力打造全球服务贸易的“首秀场”。本届服贸会围绕培育发展新质生产力，集中展示了服务贸易数字化、智能化、绿色化发展的最新成果、最新技术和最新应用，陆续发布了200 余项创新成果。",
    reference: "CIFTIS is a vivid portrayal of the high-quality development of China's service industry and service trade. In the first half of this year, China's service trade scale hit a historical high, with the total volume of service imports and exports reaching 3.6 trillion yuan, marking a 14% increase year-on-year. China is driving the high-quality development of service trade through high-level openness, contributing significantly to global economic growth.\n\nStepping into the CIFTIS exhibition area, one is immediately enveloped by the essence of digitalization, intelligentization, and greenization. Surgical robots that utilize artificial intelligence deep learning technology can assist doctors in creating personalized surgical plans based on a single CT scan; electric drones enhance efficiency in agricultural production, inspection, and firefighting... At CIFTIS, many institutions and enterprises debut new technologies and achievements, setting the pace for industry innovation trends.\n\nServing as a vital platform for international cooperation in service trade, CIFTIS strives to establish itself as the “premiere platform”for global service trade. This year's CIFTIS, centered on nurturing the development of new quglity productive forces, has concentrated on displaying the latest outcomes, technologies, and applications in the digitalization, intelligentization, and greenization of service trade, and has sequentially unveiled over 200 innovative achievements.",
  },
  {
    id: "art-sample-zh-to-en-4",
    domain: "sample",
    direction: "zh-to-en",
    batch: 4,
    title: "样题 2025 经济领域 | 海关总署外贸数据",
    units: 293,
    text: "海关总署发布的数据显示，2023年前4个月，我国进出口总值13.32万亿元，同比增长5.8%，进出口延续了向好态势。外贸进出口展现出较强韧性，为全年实现外贸促稳提质打下了基础。值得一提的是，今年前4个月，有进出口实绩的民营企业数量同比增加了8.9%，为拓宽就业渠道、稳定就业大盘发挥了积极作用。\n\n外贸平稳向好，得益于我国产业链水平不断提升。高技术、高附加值、引领绿色转型的产品领跑出口，表明我国外贸新动能不断培育壮大，更折射出供给侧结构性改革下，中国制造业迈向高端化、智能化、绿色化的坚实足迹。依靠科技创新与低碳转型，“中国制造”不断塑造和积累国际竞争新优势，中国经济高质量发展活力强劲。",
    reference: "",
  },
  {
    id: "art-past-paper-zh-to-en-5",
    domain: "past-paper",
    direction: "zh-to-en",
    batch: 5,
    title: "真题 2024 校赛 文化领域 | 大运河与中外文明交流",
    units: 232,
    text: "运河文化串联华夏文明源远流长的历史脉络。大运河历经2500 多个春秋，延绵近3200 公里，集聚了多项物质和非物质文化遗产。千百年来，南北文化在大运河上交织融合、奔涌向前，绘就出一幅绵延千里的锦绣画卷。\n\n运河文化书写中外文明美美与共的动人故事。大运河作为古代中国联通世界的文化纽带、历史见证，展现了中华文明的开放包容精神。回溯历史，运河曾承载过中国丝绸、瓷器、茶叶等物产的外运，无数中外文化使者的游历。千帆过尽的大运河不仅是中华民族的瑰宝，更是与世界文化互联互通的桥梁。",
    reference: "Canal culture weaves together the long and rich history of Chinese civilization. The Grand Canal, spanning over 2, 500 years and nearly 3, 200 kilometers, embodies numerous tangible and intangible cultural heritages. For centuries, northern and southern cultures have intertwined and surged forward along the Grand Canal, creating a magnificent tapestry that stretches for miles.\n\nCanal culture tells a touching story of the harmonious coexistence of Chinese and foreign civilizations. As an ancient cultural link connecting China to the world, the Grand Canal showcases the open and inclusive spirit of Chinese civilization. Historically, it facilitated the export of silk, porcelain, and tea, along with the journeys of countless cultural ambassadors from both China and abroad. The Grand Canal. with its many sails passing by, is not only a treasure of the Chinese nation but also a bridge for cultural connectivity with the world.",
  },
  {
    id: "art-sample-zh-to-en-5",
    domain: "sample",
    direction: "zh-to-en",
    batch: 5,
    title: "样题 2025 文化领域 | 译后编辑：中国共产党百年历程",
    units: 233,
    text: "“大鹏一日同风起，扶摇直上九万里。”100年来，中国共产党秉持为中国人民谋幸福的初心、为中华民族谋复兴的使命，不畏艰难险阻，不惧流血牺牲，团结带领全国各族人民浴血奋斗、发愤图强、改革开放，中华民族迎来了从站起来、富起来到强起来的伟大飞跃。今天，中国共产党已经发展成为一个走过百年光辉历程、在最大的社会主义国家执政70多年、拥有9100多万党员的世界上最大的马克思主义执政党，得到了14亿中国人民最广泛的支持和拥护。中国共产党立志于中华民族千秋伟业，百年恰是风华正茂！",
    reference: "",
  },
  {
    id: "art-past-paper-zh-to-en-6",
    domain: "past-paper",
    direction: "zh-to-en",
    batch: 6,
    title: "真题 2025 初赛 文化领域 | 「北京中轴线」列入世界遗产名录",
    units: 297,
    text: "2024年7月27日，联合国教科文组织第46届世界遗产大会通过决议，将“北京中轴线”列入《世界遗产名录》。“北京中轴线”纵贯北京老城南北，始建于13世纪，形成于16世纪，此后经不断演进发展，形成今天全长7.8公里、世界上最长的城市轴线。“北京中轴线”选址、格局、城市形态和设计展现了中国古代王朝制度和城市规划传统，见证了北京城市的发展演变。世界遗产委员会认为，“北京中轴线”所体现的中国传统都城规划理论和“中”“和”哲学思想，为世界城市规划史作出了重要贡献。今后，中国将继续做好世界文化遗产保护管理工作，进一步加强与国际组织和各缔约国的交流合作，为推动文明交流互鉴、构建人类命运共同体贡献力量。",
    reference: "On July 27, 2024, the 46th session of the World Heritage Committee of the United Nations Educational, Scientific and Cultural Organization adopted a resolution to inscribe the “Beijing Central Axis” on the World Heritage List. The “Beijing Central Axis” runs through the old city of Beijing from north to south. It originated in the 13th century, took shape in the 16th century, and has since continuously evolved and developed, forming today's 7.8-kilometer-long urban axis, the longest in the world. The site selection, layout, urban form and design of the “Beijing Central Axis” demonstrate the traditions of China's ancient dynastic systems and urban planning, and witness the development and evolution of Beijing as a city. The World Heritage Committee believes that the “Beijing Central Axis” embodies the Chinese traditional regional planning theory of “harmony” and “the mean” as well as philosophical thinking, and has made important contributions to the history of world urban planning. In the future, China will continue to do a good job in the protection and management of world cultural heritage, further strengthen exchanges and cooperation with international organizations and State Parties, and contribute to promoting cultural exchanges and mutual learning and building a community with a shared future for mankind.",
  },
  {
    id: "art-sample-zh-to-en-6",
    domain: "sample",
    direction: "zh-to-en",
    batch: 6,
    title: "样题 2025 社会领域 | 新闻编译：社区国家宪法日宣传",
    units: 677,
    text: "在浙江省嘉兴市新塍镇虹桥社区，11月29日上午就迎来了“12·4”国家宪法日宣传活动的一个高潮。\n\n在活动现场，一大早就气氛热烈，前来参加活动的社区居民把活动现场围了个满满当当。“有文艺演出，还有知识竞赛，这种形式还是蛮吸引人的。”已经退休的李阿姨对于即将开始的宣传活动充满期待。\n\n实际上，相关准备工作或者说热身活动早已开始。为了这个竞赛，前期社区已经专门组织了“法律明白人”培训班，而参加这个竞赛的正是培训班学员。他们分别组成了6个竞赛小组，在经过紧张的必答、抢答环节后一决胜负。\n\n在竞赛中时常穿插进来的文艺节目，更是老百姓喜闻乐见的。名为“厚德载物”“少年中国”“红领巾”的一系列文艺节目，融入了浓浓的法治宣传元素，内容积极向上充满正能量，在欣赏文艺演出的同时让法治宣传深入人心、得到活化。\n\n虹桥社区举行的上述活动，是全国无数个社区正在进行的宪法宣传活动的一个缩影。\n\n早在11月24日，民政部办公厅、司法部办公厅就共同制定印发了《2020年全国“宪法进社区”主题宣传活动工作方案》（以下简称《方案》），明确活动旨在深入学习贯彻党的十九大和十九届二中、三中、四中、五中全会精神，推动全国广大社区居民和社区组织深入学习宪法，弘扬宪法精神，维护宪法权威，推动宪法全面实施，主题为“深入学习宣传习近平法治思想 大力弘扬宪法精神”。\n\n《方案》要求围绕社区居民法治需求和关注的热点问题，结合“宪法进万家”活动，深入基层社区、家庭开展普法宣传。突出宣传宪法关于公民基本权利和义务的规定，关于居民委员会有关规定，推进基层依法治理。充分利用市民讲堂、道德讲堂等阵地为社区居民讲法治课。",
    reference: "",
  },
  {
    id: "art-sample-zh-to-en-7",
    domain: "sample",
    direction: "zh-to-en",
    batch: 7,
    title: "样题 2025 文化领域 | 文学翻译：柯灵《乡土情结》开篇",
    units: 321,
    text: "每个人的心里，都有一方魂牵梦萦的土地。得意时想到它，失意时想到它。逢年逢节，触景生情，随时随地想到它。海天茫茫，风尘碌碌，酒阑灯灺人散后，良辰美景奈何天，洛阳秋风，巴山夜雨，都会情不自禁地惦念它。离得远了久了，使人愁肠百结：“客舍并州数十霜，归心日夜忆咸阳，无端又渡桑乾水，却望并州是故乡。”好不容易能回家了，偏又忐忑不安：“岭外音书断，经冬复历春。近乡情更怯，不敢问来人。”异乡人这三个字，听起来音色苍凉：“他乡遇故知”，则是人生一快。一个怯生生的船家女，偶尔在江上听到乡音，就不觉喜上眉梢，顾不得娇羞，和隔船的陌生男子搭讪：“君家何处住？妾住在横塘。停船暂借问，或恐是同乡。”辽阔的空间，悠邈的时间，都不会使这种感情褪色：这就是乡土情结。",
    reference: "",
  },
  {
    id: "art-sample-zh-to-en-8",
    domain: "sample",
    direction: "zh-to-en",
    batch: 8,
    title: "样题 2026 经济领域 | 海关总署外贸数据",
    units: 293,
    text: "海关总署发布的数据显示，2023年前4个月，我国进出口总值13.32万亿元，同比增长5.8%，进出口延续了向好态势。外贸进出口展现出较强韧性，为全年实现外贸促稳提质打下了基础。值得一提的是，今年前4个月，有进出口实绩的民营企业数量同比增加了8.9%，为拓宽就业渠道、稳定就业大盘发挥了积极作用。\n\n外贸平稳向好，得益于我国产业链水平不断提升。高技术、高附加值、引领绿色转型的产品领跑出口，表明我国外贸新动能不断培育壮大，更折射出供给侧结构性改革下，中国制造业迈向高端化、智能化、绿色化的坚实足迹。依靠科技创新与低碳转型，“中国制造”不断塑造和积累国际竞争新优势，中国经济高质量发展活力强劲。",
    reference: "",
  },
]
